// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NestoTamoBlazor.Server;

namespace NestoTamoBlazor.Server.Migrations
{
    [DbContext(typeof(Baza))]
    partial class BazaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NestoTamoBlazor.Shared.Adresa", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Korisnik_FK")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Korisnik_FK");

                    b.ToTable("Adresas");

                    b.HasData(
                        new
                        {
                            ID = "a",
                            Broj = "111",
                            Korisnik_FK = -1,
                            Ulica = "abc"
                        },
                        new
                        {
                            ID = "b",
                            Broj = "222",
                            Korisnik_FK = -1,
                            Ulica = "zxc"
                        },
                        new
                        {
                            ID = "c",
                            Broj = "333",
                            Korisnik_FK = -2,
                            Ulica = "qwe"
                        });
                });

            modelBuilder.Entity("NestoTamoBlazor.Shared.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Korisniks");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Ime = "Pera",
                            Prezime = "Peric"
                        },
                        new
                        {
                            ID = -2,
                            Ime = "Neko",
                            Prezime = "Nekic"
                        });
                });

            modelBuilder.Entity("NestoTamoBlazor.Shared.Adresa", b =>
                {
                    b.HasOne("NestoTamoBlazor.Shared.Korisnik", "Korisnik")
                        .WithMany("Adrese")
                        .HasForeignKey("Korisnik_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
